# Generated by Django 5.2.5 on 2025-08-26 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('tin_number', models.CharField(max_length=50, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('enterprise_type', models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('limited_company', 'Limited Company'), ('cooperative', 'Cooperative'), ('ngo', 'NGO')], max_length=50)),
                ('enterprise_size', models.CharField(choices=[('micro', 'Micro (1-4 employees)'), ('small', 'Small (5-30 employees)'), ('medium', 'Medium (31-100 employees)')], max_length=50)),
                ('sector', models.CharField(choices=[('agriculture', 'Agriculture'), ('manufacturing', 'Manufacturing'), ('services', 'Services'), ('technology', 'Technology'), ('retail', 'Retail'), ('construction', 'Construction'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('finance', 'Finance'), ('other', 'Other')], max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('year_established', models.PositiveIntegerField()),
                ('number_of_employees', models.PositiveIntegerField()),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_vetted', models.BooleanField(default=False)),
                ('vetted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise', to=settings.AUTH_USER_MODEL)),
                ('vetted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetted_enterprises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration_certificate', 'Registration Certificate'), ('tax_clearance', 'Tax Clearance'), ('business_license', 'Business License'), ('financial_statement', 'Financial Statement'), ('bank_statement', 'Bank Statement'), ('audit_report', 'Audit Report'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='enterprise_documents/')),
                ('fiscal_year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('extracted_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('extracted_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('extracted_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='enterprises.enterprise')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
