# Generated by Django 5.2.5 on 2025-08-27 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='documents_requested',
            field=models.TextField(blank=True, help_text='Specific documents requested from enterprise', null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes about verification status', null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('documents_requested', 'Documents Requested')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='enterprisedocument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enterprisedocument',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprisedocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprisedocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
