# Generated by Django 5.2.5 on 2026-01-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0002_enterprise_documents_requested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='address',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='city',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='enterprise_size',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='management_structure',
            field=models.CharField(choices=[('owner_managed', 'Owner-managed'), ('professional_management', 'Professional Management')], default='owner_managed', max_length=50),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='province',
            field=models.CharField(choices=[('kigali_city', 'Kigali City'), ('eastern', 'Eastern Province'), ('western', 'Western Province'), ('northern', 'Northern Province'), ('southern', 'Southern Province')], default='kigali_city', max_length=50),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
