# Generated by Django 5.2.5 on 2026-03-05 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0003_remove_enterprise_address_remove_enterprise_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfileForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('agriculture', 'Agriculture'), ('manufacturing', 'Manufacturing'), ('services', 'Services'), ('technology', 'Technology'), ('retail', 'Retail'), ('construction', 'Construction'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('finance', 'Finance'), ('other', 'Other')], help_text='One form template per sector', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profile_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sector'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='enterprises.businessprofileform')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('long_text', 'Long Text / Paragraph'), ('number', 'Number'), ('choice', 'Multiple Choice (single)'), ('multi_choice', 'Multiple Choice (multi)'), ('date', 'Date'), ('file', 'File Upload'), ('auto_fill', 'Auto-fill from Profile')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('help_text', models.TextField(blank=True)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('choices', models.JSONField(blank=True, default=list, help_text="[{value: 'x', label: 'X'}, ...]")),
                ('accepted_file_types', models.JSONField(blank=True, default=list, help_text="['.pdf', '.docx', ...]")),
                ('max_file_size_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_fill_source', models.CharField(blank=True, max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='enterprises.businessprofilesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseProfileFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_form_response', to='enterprises.enterprise')),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_responses', to='enterprises.businessprofileform')),
            ],
        ),
    ]
