# Generated by Django 5.2.5 on 2025-12-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('enterprise', 'Enterprise'), ('investor', 'Investor')], default='enterprise', max_length=20),
        ),
    ]
