# Generated by Django 5.2.5 on 2026-02-06 08:35

from django.db import migrations


def populate_phone_numbers(apps, schema_editor):
    """Assign unique temporary phone numbers to existing users who don't have one."""
    User = apps.get_model('accounts', 'User')
    users_without_phone = User.objects.filter(phone_number__isnull=True) | User.objects.filter(phone_number='')
    
    for index, user in enumerate(users_without_phone, start=1):
        # Generate a unique temporary phone number in format: +250700000XXX
        temp_phone = f"+250700000{str(index).zfill(3)}"
        
        # Ensure uniqueness
        while User.objects.filter(phone_number=temp_phone).exists():
            index += 1
            temp_phone = f"+250700000{str(index).zfill(3)}"
        
        user.phone_number = temp_phone
        user.save(update_fields=['phone_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_number_alter_user_username'),
    ]

    operations = [
        migrations.RunPython(populate_phone_numbers, reverse_code=migrations.RunPython.noop),
    ]
