# Generated by Django 5.2.5 on 2025-12-03 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprises', '0002_enterprise_documents_requested_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_type', models.CharField(choices=[('individual', 'Individual Investor'), ('institutional', 'Institutional Investor'), ('vc', 'Venture Capital'), ('pe', 'Private Equity'), ('angel', 'Angel Investor'), ('bank', 'Bank/Financial Institution'), ('dfi', 'Development Finance Institution'), ('other', 'Other')], max_length=20)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('min_investment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_investment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_investors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestorCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectors', models.JSONField(default=list, help_text='List of sector codes')),
                ('min_funding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_funding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('min_readiness_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('required_documents', models.JSONField(default=list, help_text='List of required document types')),
                ('preferred_sizes', models.JSONField(default=list, help_text='List of preferred enterprise sizes')),
                ('min_years_operation', models.PositiveIntegerField(default=0)),
                ('min_employees', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='investors.investor')),
            ],
            options={
                'verbose_name_plural': 'Investor Criteria',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('match_details', models.JSONField(default=dict, help_text='Detailed breakdown of match score')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('engaged', 'Engaged'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('investor_approved', models.BooleanField(default=False)),
                ('investor_notes', models.TextField(blank=True, null=True)),
                ('enterprise_accepted', models.BooleanField(default=False)),
                ('enterprise_notes', models.TextField(blank=True, null=True)),
                ('documents_requested', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='enterprises.enterprise')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='investors.investor')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['-match_score', '-created_at'],
                'unique_together': {('investor', 'enterprise')},
            },
        ),
        migrations.CreateModel(
            name='MatchInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('document_request', 'Document Request'), ('document_submission', 'Document Submission'), ('message', 'Message'), ('meeting_request', 'Meeting Request'), ('status_change', 'Status Change')], max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='investors.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
