# Generated by Django 5.2.5 on 2025-12-21 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaignmessage'),
        ('investors', '0002_alter_match_unique_together_match_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='campaigns.campaign'),
        ),
    ]
