# Generated by Django 5.2.5 on 2025-12-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_alter_match_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='payment_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
