# Generated by Django 5.2.5 on 2026-02-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_match_payment_received_match_payment_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='partner_name',
            field=models.CharField(blank=True, help_text='Name of the partner contact person', max_length=255, null=True),
        ),
    ]
