# Generated by Django 5.2.5 on 2026-02-20 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_investor_partner_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='investorcriteria',
            name='auto_reject_below_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Automatically reject applications below this readiness score', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='investorcriteria',
            name='preferred_revenue_range',
            field=models.JSONField(blank=True, default=dict, help_text='Preferred revenue range: {min: X, max: Y}'),
        ),
        migrations.AlterField(
            model_name='investorcriteria',
            name='required_documents',
            field=models.JSONField(default=list, help_text="Array of document requirements: [{name: 'Financial Statements', type: 'financial_statement', required: True, description: '...'}]"),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('long_text', 'Long Text / Paragraph'), ('number', 'Number'), ('choice', 'Multiple Choice'), ('file', 'File Upload'), ('auto_fill', 'Auto-filled from Profile/Assessment')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('help_text', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('choices', models.JSONField(blank=True, default=list, help_text="Array of choice objects: [{value: 'x', label: 'X'}]")),
                ('accepted_file_types', models.JSONField(blank=True, default=list, help_text="Array of accepted file extensions: ['.pdf', '.docx']")),
                ('max_file_size_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_fill_source', models.CharField(blank=True, help_text="Dot notation for data source: 'profile.business_name', 'assessment.readiness_score'", max_length=255)),
                ('conditional_rules', models.JSONField(blank=True, default=dict, help_text="Rules to show/hide field: {show_if: {field: 'loan_amount', operator: '>', value: 10000000}}")),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='investors.formsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerFundingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., BK SME Loan Application', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('funding_type', models.CharField(choices=[('loan', 'Loan'), ('equity', 'Equity Investment'), ('grant', 'Grant'), ('hybrid', 'Hybrid')], max_length=20)),
                ('min_readiness_score', models.DecimalField(blank=True, decimal_places=2, help_text="Override partner's default min readiness score for this form", max_digits=5, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_funding_forms', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_forms', to='investors.investor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('partner', 'name', 'version')},
            },
        ),
        migrations.AddField(
            model_name='formsection',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='investors.partnerfundingform'),
        ),
    ]
