"""
Management command: seed_default_form

Creates (or recreates) the default SME application form used as a fallback
when a user's chosen sector has no dedicated profile form.

The form structure mirrors the standard credit-application CSV spec:
  Basic Profile | Ownership | Loan Request | Loan Purpose | Financing Plan |
  Business Model | Market | Financial Snapshot | Existing Debt |
  Collateral | Site Verification

Usage:
    python manage.py seed_default_form          # create / update
    python manage.py seed_default_form --reset  # delete existing then recreate
"""

from django.core.management.base import BaseCommand
from enterprises.models import (
    BusinessProfileForm,
    BusinessProfileSection,
    BusinessProfileField,
)

# ─── Form definition ──────────────────────────────────────────────────────────

FORM_NAME = "Standard SME Application Form"
FORM_DESCRIPTION = (
    "Default application form for SMEs whose sector does not yet have a "
    "dedicated profile form. Covers basic profile, ownership, loan request, "
    "financing plan, business model, market, financials, collateral, and "
    "site verification."
)

# Each section: (title, description, order, [fields])
# Each field: (label, field_type, is_required, mandatory_note, help_text,
#              placeholder, choices, accepted_file_types, auto_fill_source,
#              min_value, max_value)
#
# field_type values: text | long_text | number | choice | multi_choice | file | auto_fill
# choices: list of {value, label} dicts (empty for non-choice fields)

SECTIONS = [
    {
        "title": "Basic Profile",
        "description": "Core business identification and registration details.",
        "order": 1,
        "fields": [
            {
                "label": "Business Legal Name",
                "field_type": "auto_fill",
                "auto_fill_source": "business_name",
                "is_required": True,
                "help_text": "The full legal name of your registered business.",
                "placeholder": "Enter legal business name",
                "choices": [],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 1,
            },
            {
                "label": "Trading Name",
                "field_type": "text",
                "auto_fill_source": "",
                "is_required": False,
                "help_text": "Name under which the business trades if different from legal name.",
                "placeholder": "Enter trading name (if different)",
                "choices": [],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 2,
            },
            {
                "label": "Registration Number",
                "field_type": "auto_fill",
                "auto_fill_source": "registration_number",
                "is_required": True,
                "help_text": "Company registration number as issued by RDB.",
                "placeholder": "e.g. 102374859",
                "choices": [],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 3,
            },
            {
                "label": "Year of Establishment",
                "field_type": "auto_fill",
                "auto_fill_source": "year_established",
                "is_required": True,
                "help_text": "The year the business was officially registered or started operations.",
                "placeholder": "e.g. 2015",
                "choices": [],
                "accepted_file_types": [],
                "min_value": 1900,
                "max_value": None,
                "order": 4,
            },
            {
                "label": "Legal Structure",
                "field_type": "auto_fill",
                "auto_fill_source": "enterprise_type",
                "is_required": True,
                "help_text": "The legal form of your business entity.",
                "placeholder": "",
                "choices": [
                    {"value": "sole_proprietorship", "label": "Sole Proprietorship"},
                    {"value": "partnership", "label": "Partnership"},
                    {"value": "limited_company", "label": "Limited Company"},
                    {"value": "cooperative", "label": "Cooperative"},
                    {"value": "ngo", "label": "NGO"},
                ],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 5,
            },
            {
                "label": "TIN",
                "field_type": "auto_fill",
                "auto_fill_source": "tin_number",
                "is_required": True,
                "help_text": "9-digit Tax Identification Number issued by RRA.",
                "placeholder": "123456789",
                "choices": [],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 6,
            },
            {
                "label": "Business Sector",
                "field_type": "auto_fill",
                "auto_fill_source": "sector",
                "is_required": True,
                "help_text": "Primary sector in which the business operates.",
                "placeholder": "",
                "choices": [
                    {"value": "agriculture", "label": "Agriculture"},
                    {"value": "manufacturing", "label": "Manufacturing"},
                    {"value": "services", "label": "Services"},
                    {"value": "technology", "label": "Technology"},
                    {"value": "retail", "label": "Retail"},
                    {"value": "construction", "label": "Construction"},
                    {"value": "healthcare", "label": "Healthcare"},
                    {"value": "education", "label": "Education"},
                    {"value": "finance", "label": "Finance"},
                    {"value": "other", "label": "Other"},
                ],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 7,
            },
            {
                "label": "Main Business Activity",
                "field_type": "long_text",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Describe the core products or services your business provides.",
                "placeholder": "Describe your primary business activity...",
                "choices": [],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 8,
            },
            {
                "label": "Business Location (Province)",
                "field_type": "auto_fill",
                "auto_fill_source": "province",
                "is_required": True,
                "help_text": "Province where the business is primarily located.",
                "placeholder": "",
                "choices": [
                    {"value": "kigali_city", "label": "Kigali City"},
                    {"value": "eastern", "label": "Eastern Province"},
                    {"value": "western", "label": "Western Province"},
                    {"value": "northern", "label": "Northern Province"},
                    {"value": "southern", "label": "Southern Province"},
                ],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 9,
            },
            {
                "label": "Registration Certificate",
                "field_type": "file",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Upload your RDB certificate of incorporation (PDF or JPG).",
                "placeholder": "",
                "choices": [],
                "accepted_file_types": [".pdf", ".jpg", ".jpeg"],
                "min_value": None,
                "max_value": None,
                "order": 10,
            },
        ],
    },
    {
        "title": "Ownership",
        "description": "Shareholder and CRB consent information.",
        "order": 2,
        "fields": [
            {
                "label": "Number of Shareholders",
                "field_type": "number",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Total number of shareholders or owners in the business.",
                "placeholder": "e.g. 2",
                "choices": [],
                "accepted_file_types": [],
                "min_value": 1,
                "max_value": None,
                "order": 1,
            },
            {
                "label": "Shareholder Names",
                "field_type": "long_text",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "List all shareholder names, one per line.",
                "placeholder": "John Doe\nJane Smith",
                "choices": [],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 2,
            },
            {
                "label": "Shareholder ID Numbers",
                "field_type": "long_text",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "National ID or passport numbers for each shareholder, one per line.",
                "placeholder": "1199780012345678\n1198560098765432",
                "choices": [],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 3,
            },
            {
                "label": "Shareholding Percentages (%)",
                "field_type": "long_text",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Ownership percentage for each shareholder (must total 100%). One per line.",
                "placeholder": "60\n40",
                "choices": [],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 4,
            },
            {
                "label": "CRB Consent",
                "field_type": "choice",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "All shareholders must consent to a Credit Reference Bureau (CRB) check.",
                "placeholder": "",
                "choices": [
                    {"value": "yes", "label": "Yes – all shareholders consent to CRB check"},
                    {"value": "no", "label": "No"},
                ],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 5,
            },
        ],
    },
    {
        "title": "Loan Request",
        "description": "Details about the financing facility being requested.",
        "order": 3,
        "fields": [
            {
                "label": "Facility Type",
                "field_type": "choice",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "The type of credit facility you are applying for.",
                "placeholder": "",
                "choices": [
                    {"value": "term_loan", "label": "Term Loan"},
                    {"value": "working_capital", "label": "Working Capital Loan"},
                    {"value": "overdraft", "label": "Overdraft"},
                    {"value": "asset_finance", "label": "Asset Finance"},
                    {"value": "mortgage", "label": "Mortgage"},
                    {"value": "trade_finance", "label": "Trade Finance"},
                ],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 1,
            },
            {
                "label": "Requested Amount (RWF)",
                "field_type": "number",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Total loan amount requested in Rwandan Francs.",
                "placeholder": "e.g. 5000000",
                "choices": [],
                "accepted_file_types": [],
                "min_value": 0,
                "max_value": None,
                "order": 2,
            },
            {
                "label": "Loan Term (Months)",
                "field_type": "choice",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Desired repayment period in months.",
                "placeholder": "",
                "choices": [
                    {"value": "3", "label": "3 months"},
                    {"value": "6", "label": "6 months"},
                    {"value": "12", "label": "12 months"},
                    {"value": "18", "label": "18 months"},
                    {"value": "24", "label": "24 months"},
                    {"value": "36", "label": "36 months"},
                    {"value": "48", "label": "48 months"},
                    {"value": "60", "label": "60 months"},
                    {"value": "84", "label": "84 months"},
                    {"value": "120", "label": "120 months"},
                ],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 3,
            },
            {
                "label": "Repayment Frequency",
                "field_type": "choice",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "How often you will make repayments.",
                "placeholder": "",
                "choices": [
                    {"value": "monthly", "label": "Monthly"},
                    {"value": "quarterly", "label": "Quarterly"},
                    {"value": "bi_annual", "label": "Bi-annual"},
                    {"value": "annual", "label": "Annual"},
                ],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 4,
            },
            {
                "label": "Grace Period Required?",
                "field_type": "choice",
                "auto_fill_source": "",
                "is_required": False,
                "help_text": "Do you require a grace period before repayments begin?",
                "placeholder": "",
                "choices": [
                    {"value": "no", "label": "No"},
                    {"value": "yes_3", "label": "Yes – 3 months"},
                    {"value": "yes_6", "label": "Yes – 6 months"},
                    {"value": "yes_12", "label": "Yes – 12 months"},
                ],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 5,
            },
            {
                "label": "Subsidy Program",
                "field_type": "choice",
                "auto_fill_source": "",
                "is_required": False,
                "help_text": "Are you applying under a specific government or development subsidy program?",
                "placeholder": "",
                "choices": [
                    {"value": "none", "label": "None"},
                    {"value": "brd", "label": "BRD (Development Bank of Rwanda)"},
                    {"value": "minagri", "label": "MINAGRI Agricultural Support"},
                    {"value": "nirda", "label": "NIRDA Industrial Support"},
                    {"value": "sme_guarantee", "label": "SME Guarantee Scheme"},
                    {"value": "other", "label": "Other"},
                ],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 6,
            },
        ],
    },
    {
        "title": "Loan Purpose",
        "description": "How the requested funds will be used.",
        "order": 4,
        "fields": [
            {
                "label": "Primary Purpose",
                "field_type": "choice",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "The main purpose for which the loan will be used.",
                "placeholder": "",
                "choices": [
                    {"value": "working_capital", "label": "Working Capital"},
                    {"value": "equipment_purchase", "label": "Equipment / Machinery Purchase"},
                    {"value": "vehicle", "label": "Vehicle Purchase"},
                    {"value": "real_estate", "label": "Real Estate / Construction"},
                    {"value": "import_finance", "label": "Import Finance"},
                    {"value": "refinancing", "label": "Debt Refinancing"},
                    {"value": "expansion", "label": "Business Expansion"},
                    {"value": "other", "label": "Other"},
                ],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 1,
            },
            {
                "label": "Detailed Description of Loan Purpose",
                "field_type": "long_text",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Provide a detailed explanation of how the loan funds will be used (max 300 words).",
                "placeholder": "Describe the specific use of funds, expected outcomes, and how it will benefit the business...",
                "choices": [],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 2,
            },
        ],
    },
    {
        "title": "Financing Plan",
        "description": "Itemised breakdown of how the loan will be allocated.",
        "order": 5,
        "fields": [
            {
                "label": "Item(s) to be Financed",
                "field_type": "long_text",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "List each item to be purchased or financed, one per line.",
                "placeholder": "e.g.: Dairy cow × 10\nMilking machine × 1\nStorage tank × 2",
                "choices": [],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 1,
            },
            {
                "label": "Total Quantity",
                "field_type": "number",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Total number of units across all items.",
                "placeholder": "e.g. 13",
                "choices": [],
                "accepted_file_types": [],
                "min_value": 1,
                "max_value": None,
                "order": 2,
            },
            {
                "label": "Total Unit Cost (RWF)",
                "field_type": "number",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Total cost of all items (RWF). This should match or be close to the requested loan amount.",
                "placeholder": "e.g. 5000000",
                "choices": [],
                "accepted_file_types": [],
                "min_value": 0,
                "max_value": None,
                "order": 3,
            },
            {
                "label": "Equity / Own Contribution (RWF)",
                "field_type": "number",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Amount you will contribute from your own funds towards this investment.",
                "placeholder": "e.g. 1000000",
                "choices": [],
                "accepted_file_types": [],
                "min_value": 0,
                "max_value": None,
                "order": 4,
            },
            {
                "label": "Proforma Invoice / Quotation",
                "field_type": "file",
                "auto_fill_source": "",
                "is_required": False,
                "help_text": "Upload a proforma invoice or supplier quotation (required for equipment, vehicles, or asset purchases).",
                "placeholder": "",
                "choices": [],
                "accepted_file_types": [".pdf", ".jpg", ".jpeg", ".png"],
                "min_value": None,
                "max_value": None,
                "order": 5,
            },
        ],
    },
    {
        "title": "Business Model",
        "description": "How your business sources, sells, and operates day-to-day.",
        "order": 6,
        "fields": [
            {
                "label": "Source of Goods / Inputs",
                "field_type": "choice",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Where does your business primarily source its goods or raw materials?",
                "placeholder": "",
                "choices": [
                    {"value": "local_market", "label": "Local Market"},
                    {"value": "imports", "label": "Imports"},
                    {"value": "own_production", "label": "Own Production / Farming"},
                    {"value": "mixed", "label": "Mixed (Local + Imports)"},
                ],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 1,
            },
            {
                "label": "Sales Model",
                "field_type": "multi_choice",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Select all sales channels your business uses.",
                "placeholder": "",
                "choices": [
                    {"value": "cash_sales", "label": "Cash Sales"},
                    {"value": "credit_sales", "label": "Credit Sales"},
                    {"value": "mobile_money", "label": "Mobile Money"},
                    {"value": "bank_transfer", "label": "Bank Transfer"},
                    {"value": "export", "label": "Export"},
                ],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 2,
            },
            {
                "label": "Credit Period Given to Customers (Days)",
                "field_type": "choice",
                "auto_fill_source": "",
                "is_required": False,
                "help_text": "If you offer credit sales, how long do customers typically take to pay?",
                "placeholder": "",
                "choices": [
                    {"value": "0", "label": "N/A – Cash sales only"},
                    {"value": "7", "label": "7 days"},
                    {"value": "14", "label": "14 days"},
                    {"value": "30", "label": "30 days"},
                    {"value": "60", "label": "60 days"},
                    {"value": "90", "label": "90 days"},
                ],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 3,
            },
            {
                "label": "Inventory Holding Period (Days)",
                "field_type": "number",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "On average, how many days does stock sit in your warehouse before being sold?",
                "placeholder": "e.g. 30",
                "choices": [],
                "accepted_file_types": [],
                "min_value": 0,
                "max_value": None,
                "order": 4,
            },
            {
                "label": "Average Monthly Operating Expenses (RWF)",
                "field_type": "number",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Total monthly costs including salaries, rent, utilities, and other overheads.",
                "placeholder": "e.g. 800000",
                "choices": [],
                "accepted_file_types": [],
                "min_value": 0,
                "max_value": None,
                "order": 5,
            },
        ],
    },
    {
        "title": "Market",
        "description": "Your market presence, competitive position, and key risks.",
        "order": 7,
        "fields": [
            {
                "label": "Geographic Reach",
                "field_type": "choice",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "The geographic area your business currently serves.",
                "placeholder": "",
                "choices": [
                    {"value": "local_district", "label": "Local / District"},
                    {"value": "provincial", "label": "Provincial"},
                    {"value": "national", "label": "National"},
                    {"value": "regional", "label": "East Africa Regional"},
                    {"value": "international", "label": "International"},
                ],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 1,
            },
            {
                "label": "Competitive Advantage",
                "field_type": "long_text",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Describe what differentiates your business from competitors.",
                "placeholder": "e.g. Unique product, lower cost, location, quality, established customer base...",
                "choices": [],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 2,
            },
            {
                "label": "Key Industry Risks",
                "field_type": "multi_choice",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Select all key risks that could affect your business.",
                "placeholder": "",
                "choices": [
                    {"value": "competition", "label": "High Competition"},
                    {"value": "climate", "label": "Climate / Weather Risk"},
                    {"value": "currency", "label": "Currency / Exchange Rate Risk"},
                    {"value": "regulatory", "label": "Regulatory / Policy Changes"},
                    {"value": "supply_chain", "label": "Supply Chain Disruption"},
                    {"value": "price_volatility", "label": "Input / Output Price Volatility"},
                    {"value": "demand", "label": "Low or Seasonal Demand"},
                    {"value": "technology", "label": "Technology Disruption"},
                ],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 3,
            },
        ],
    },
    {
        "title": "Financial Snapshot",
        "description": "Recent financial performance of the business.",
        "order": 8,
        "fields": [
            {
                "label": "Annual Revenue – Last Financial Year (RWF)",
                "field_type": "number",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Total sales or revenue for the most recently completed financial year.",
                "placeholder": "e.g. 12000000",
                "choices": [],
                "accepted_file_types": [],
                "min_value": 0,
                "max_value": None,
                "order": 1,
            },
            {
                "label": "Revenue Growth (% Year-on-Year)",
                "field_type": "number",
                "auto_fill_source": "",
                "is_required": False,
                "help_text": "Approximate percentage growth in revenue compared to the prior year. Use negative for decline.",
                "placeholder": "e.g. 15 (for 15% growth)",
                "choices": [],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 2,
            },
            {
                "label": "Average Monthly Bank Deposits (RWF)",
                "field_type": "number",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Average total deposits into your business bank account per month (last 6 months).",
                "placeholder": "e.g. 1500000",
                "choices": [],
                "accepted_file_types": [],
                "min_value": 0,
                "max_value": None,
                "order": 3,
            },
            {
                "label": "Bank Statement (Last 6–12 Months)",
                "field_type": "file",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Upload official bank statements covering the last 6 to 12 months.",
                "placeholder": "",
                "choices": [],
                "accepted_file_types": [".pdf", ".jpg", ".jpeg", ".xlsx", ".xls"],
                "min_value": None,
                "max_value": None,
                "order": 4,
            },
        ],
    },
    {
        "title": "Existing Debt",
        "description": "Details about any current loans or credit obligations.",
        "order": 9,
        "fields": [
            {
                "label": "Do you have existing loans?",
                "field_type": "choice",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Indicate whether your business currently has any outstanding loans.",
                "placeholder": "",
                "choices": [
                    {"value": "no", "label": "No – no existing loans"},
                    {"value": "yes", "label": "Yes – I have existing loan(s)"},
                ],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 1,
            },
            {
                "label": "Total Outstanding Balance (RWF)",
                "field_type": "number",
                "auto_fill_source": "",
                "is_required": False,
                "help_text": "Total remaining balance on all existing loans (if applicable).",
                "placeholder": "e.g. 2000000",
                "choices": [],
                "accepted_file_types": [],
                "min_value": 0,
                "max_value": None,
                "order": 2,
            },
            {
                "label": "Combined Monthly Installment (RWF)",
                "field_type": "number",
                "auto_fill_source": "",
                "is_required": False,
                "help_text": "Total monthly repayment amount across all existing loans.",
                "placeholder": "e.g. 150000",
                "choices": [],
                "accepted_file_types": [],
                "min_value": 0,
                "max_value": None,
                "order": 3,
            },
        ],
    },
    {
        "title": "Collateral",
        "description": "Assets offered as security for the loan.",
        "order": 10,
        "fields": [
            {
                "label": "Collateral Type",
                "field_type": "choice",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "The type of collateral you are offering to secure this loan.",
                "placeholder": "",
                "choices": [
                    {"value": "land_property", "label": "Land / Immovable Property"},
                    {"value": "vehicle", "label": "Vehicle"},
                    {"value": "equipment", "label": "Equipment / Machinery"},
                    {"value": "stock", "label": "Stock / Inventory"},
                    {"value": "shares", "label": "Shares / Investments"},
                    {"value": "guarantor", "label": "Personal / Corporate Guarantee"},
                    {"value": "none", "label": "None (Unsecured)"},
                ],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 1,
            },
            {
                "label": "Property UPI (if Land / Property)",
                "field_type": "text",
                "auto_fill_source": "",
                "is_required": False,
                "help_text": "Unique Parcel Identifier (UPI) as shown on the land title.",
                "placeholder": "e.g. 1/01/02/01/1234",
                "choices": [],
                "accepted_file_types": [],
                "min_value": None,
                "max_value": None,
                "order": 2,
            },
            {
                "label": "Estimated Market Value / OMV (RWF)",
                "field_type": "number",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "Open Market Value of the collateral asset as estimated by a licensed valuer.",
                "placeholder": "e.g. 15000000",
                "choices": [],
                "accepted_file_types": [],
                "min_value": 0,
                "max_value": None,
                "order": 3,
            },
            {
                "label": "Forced Sale Value / FSV (RWF)",
                "field_type": "number",
                "auto_fill_source": "",
                "is_required": False,
                "help_text": "Estimated quick-sale value (typically 60–80% of OMV).",
                "placeholder": "e.g. 10000000",
                "choices": [],
                "accepted_file_types": [],
                "min_value": 0,
                "max_value": None,
                "order": 4,
            },
            {
                "label": "Title Deed / Ownership Document",
                "field_type": "file",
                "auto_fill_source": "",
                "is_required": False,
                "help_text": "Upload the title deed or ownership certificate for the collateral (required for land/property).",
                "placeholder": "",
                "choices": [],
                "accepted_file_types": [".pdf", ".jpg", ".jpeg"],
                "min_value": None,
                "max_value": None,
                "order": 5,
            },
        ],
    },
    {
        "title": "Site Verification",
        "description": "Photos taken at your business location for verification purposes.",
        "order": 11,
        "fields": [
            {
                "label": "Exterior Business Photo",
                "field_type": "file",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "A clear photo of the exterior of your business premises (storefront, signage, etc.).",
                "placeholder": "",
                "choices": [],
                "accepted_file_types": [".jpg", ".jpeg", ".png"],
                "min_value": None,
                "max_value": None,
                "order": 1,
            },
            {
                "label": "Interior / Stock Photo",
                "field_type": "file",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "A photo of the interior of your business or current stock/inventory.",
                "placeholder": "",
                "choices": [],
                "accepted_file_types": [".jpg", ".jpeg", ".png"],
                "min_value": None,
                "max_value": None,
                "order": 2,
            },
            {
                "label": "Owner with Business Photo",
                "field_type": "file",
                "auto_fill_source": "",
                "is_required": True,
                "help_text": "A photo of the business owner inside or in front of the business.",
                "placeholder": "",
                "choices": [],
                "accepted_file_types": [".jpg", ".jpeg", ".png"],
                "min_value": None,
                "max_value": None,
                "order": 3,
            },
        ],
    },
]


# ─── Command ──────────────────────────────────────────────────────────────────

class Command(BaseCommand):
    help = "Seed the default SME application form (shown when no sector-specific form exists)"

    def add_arguments(self, parser):
        parser.add_argument(
            "--reset",
            action="store_true",
            help="Delete and recreate the default form instead of skipping if it already exists",
        )

    def handle(self, *args, **options):
        reset = options["reset"]

        existing = BusinessProfileForm.objects.filter(is_default=True).first()
        if existing:
            if not reset:
                self.stdout.write(
                    self.style.WARNING(
                        f"Default form already exists (id={existing.id}, name='{existing.name}'). "
                        "Use --reset to delete and recreate it."
                    )
                )
                return
            self.stdout.write(f"Deleting existing default form: '{existing.name}' …")
            existing.delete()

        self.stdout.write("Creating default SME form …")

        form = BusinessProfileForm.objects.create(
            sector='_default',
            name=FORM_NAME,
            description=FORM_DESCRIPTION,
            is_active=True,
            is_default=True,
        )
        self.stdout.write(f"  Created form: '{form.name}' (sector='_default')")

        total_fields = 0
        for sec_def in SECTIONS:
            section = BusinessProfileSection.objects.create(
                form=form,
                title=sec_def["title"],
                description=sec_def["description"],
                order=sec_def["order"],
            )
            self.stdout.write(f"    Section [{sec_def['order']:02d}]: {sec_def['title']}")

            for f_def in sec_def["fields"]:
                BusinessProfileField.objects.create(
                    section=section,
                    field_type=f_def["field_type"],
                    label=f_def["label"],
                    help_text=f_def["help_text"],
                    placeholder=f_def.get("placeholder", ""),
                    is_required=f_def["is_required"],
                    order=f_def["order"],
                    choices=f_def.get("choices", []),
                    accepted_file_types=f_def.get("accepted_file_types", []),
                    auto_fill_source=f_def.get("auto_fill_source", ""),
                    min_value=f_def.get("min_value"),
                    max_value=f_def.get("max_value"),
                )
                total_fields += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"\nDone. Default form created with {len(SECTIONS)} sections and {total_fields} fields."
            )
        )
