# Generated by Django 5.2.5 on 2025-08-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('rw', 'Kinyarwanda'), ('fr', 'French'), ('sw', 'Swahili')], default='en', max_length=5),
        ),
    ]
