# Generated by Django 5.2.5 on 2025-12-06 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_questionnaire_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires', to='assessments.assessmentcategory'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='estimated_time_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Estimated completion time in minutes'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='max_employees',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of employees', null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='min_employees',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum number of employees', null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='target_districts',
            field=models.JSONField(blank=True, default=list, help_text='List of districts. Empty means all districts.'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='target_enterprise_sizes',
            field=models.JSONField(blank=True, default=list, help_text='List of enterprise sizes. Empty means all sizes.'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='target_sectors',
            field=models.JSONField(blank=True, default=list, help_text='List of sectors this questionnaire is for. Empty means all sectors.'),
        ),
    ]
