# Generated by Django 5.2.5 on 2025-12-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_questionnaire_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, help_text='When AI insights were generated', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ai_strengths',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated strengths'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ai_weaknesses',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated weaknesses'),
        ),
    ]
