# Generated by Django 5.2.5 on 2025-12-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_assessment_ai_generated_at_assessment_ai_strengths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text="Translations: {'en': 'text', 'fr': 'texte', ...}"),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text="Translations: {'en': 'text', 'fr': 'texte', ...}"),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text="Question text in the questionnaire's primary language"),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='text',
            field=models.CharField(help_text="Option text in the questionnaire's primary language", max_length=255),
        ),
    ]
