# Generated by Django 5.2.5 on 2026-01-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_add_translation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='target_enterprise_sizes',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='target_management_structures',
            field=models.JSONField(blank=True, default=list, help_text='List of management structures. Empty means all.'),
        ),
    ]
