# Generated by Django 5.2.5 on 2026-02-06 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_remove_questionnaire_target_enterprise_sizes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.PositiveIntegerField(help_text='Minimum score (inclusive) for this recommendation to apply')),
                ('max_score', models.PositiveIntegerField(help_text='Maximum score (inclusive) for this recommendation to apply')),
                ('recommendation_text', models.TextField(help_text='Recommendation text to show when score is in this range')),
                ('translations', models.JSONField(blank=True, default=dict, help_text="Translations: {'en': 'text', 'fr': 'texte', ...}")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_recommendations', to='assessments.question')),
            ],
            options={
                'ordering': ['min_score'],
            },
        ),
    ]
