# Generated by Django 5.2.5 on 2026-03-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_questionrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.CharField(blank=True, help_text='e.g. RWF 50,000 or Free', max_length=255)),
                ('contact', models.CharField(blank=True, help_text='Contact person or phone/email', max_length=255)),
                ('link', models.URLField(blank=True, help_text='External URL for more information')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='questionrecommendation',
            name='recommended_services',
            field=models.ManyToManyField(blank=True, help_text='Services to recommend alongside this recommendation', related_name='question_recommendations', to='assessments.service'),
        ),
    ]
