# Generated by Django 5.2.5 on 2026-03-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_add_service_model_and_recommended_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='recommended_services',
            field=models.ManyToManyField(blank=True, help_text='Services recommended alongside this suggestion', related_name='assessment_recommendations', to='assessments.service'),
        ),
    ]
