# Generated by Django 5.2.5 on 2025-12-03 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprises', '0002_enterprise_documents_requested_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('campaign_type', models.CharField(choices=[('equity', 'Equity Investment'), ('debt', 'Debt Financing'), ('grant', 'Grant'), ('hybrid', 'Hybrid')], max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('min_investment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('investor_count', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('vetted', 'Vetted'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('is_vetted', models.BooleanField(default=False)),
                ('vetted_at', models.DateTimeField(blank=True, null=True)),
                ('vetting_notes', models.TextField(blank=True, null=True)),
                ('use_of_funds', models.JSONField(default=dict, help_text='Breakdown of how funds will be used')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='enterprises.enterprise')),
                ('vetted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetted_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('pitch_deck', 'Pitch Deck'), ('business_plan', 'Business Plan'), ('financial_projection', 'Financial Projection'), ('term_sheet', 'Term Sheet'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='campaign_documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Visible to all investors')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('committed', 'Committed'), ('invested', 'Invested'), ('withdrawn', 'Withdrawn')], default='interested', max_length=20)),
                ('interest_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('committed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('invested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
