# Generated by Django 5.2.5 on 2025-12-03 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninterest',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_interests', to='investors.investor'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigninterest',
            unique_together={('campaign', 'investor')},
        ),
    ]
