# Generated by Django 5.2.5 on 2026-01-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaignmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='readiness_score_at_submission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='revision_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='revision_notes',
            field=models.TextField(blank=True, help_text='Notes for SME when revision is required', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('revision_required', 'Revision Required'), ('approved', 'Approved'), ('active', 'Active - Partner Visible'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
