# Generated by Django 5.2.5 on 2026-02-20 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_readiness_score_at_submission_and_more'),
        ('investors', '0006_formsection_investorcriteria_auto_reject_below_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='target_partners',
            field=models.ManyToManyField(blank=True, help_text='Specific partners this campaign is targeting. If empty, visible to all partners.', related_name='targeted_campaigns', to='investors.investor'),
        ),
        migrations.CreateModel(
            name='CampaignPartnerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('conditional', 'Conditionally Approved'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('form_responses', models.JSONField(default=dict, help_text='Responses to partner-specific form fields. Structure: {section_id: {field_id: value}}')),
                ('auto_screened', models.BooleanField(default=False)),
                ('auto_screen_passed', models.BooleanField(default=False)),
                ('auto_screen_reason', models.TextField(blank=True, help_text='Reason for auto-rejection if applicable', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('approval_conditions', models.JSONField(blank=True, default=list, help_text='List of conditions that must be met for final approval')),
                ('conditions_met', models.BooleanField(default=False)),
                ('proposed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount partner is willing to invest', max_digits=15, null=True)),
                ('proposed_terms', models.JSONField(blank=True, default=dict, help_text='Investment terms proposed by partner')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_applications', to='campaigns.campaign')),
                ('funding_form', models.ForeignKey(blank=True, help_text="The partner's funding form used for this application", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='investors.partnerfundingform')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_applications', to='investors.investor')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'partner'], name='campaigns_c_status_44cea4_idx'), models.Index(fields=['campaign', 'status'], name='campaigns_c_campaig_460150_idx')],
                'unique_together': {('campaign', 'partner')},
            },
        ),
    ]
