# Generated by Django 5.2.5 on 2026-03-05 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_target_partners_campaignpartnerapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_key', models.CharField(max_length=255)),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='application_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='campaigns.campaignpartnerapplication')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
