# Generated by Django 5.2.5 on 2026-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_partnerapplicationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninterest',
            name='enterprise_decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigninterest',
            name='enterprise_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaigninterest',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested'), ('pledged', 'Pledged'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('committed', 'Committed'), ('invested', 'Invested'), ('withdrawn', 'Withdrawn')], default='interested', max_length=20),
        ),
    ]
